//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_BookStoreCT.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Authors_Books = new HashSet<Authors_Books>();
            this.DetailBills = new HashSet<DetailBill>();
        }
    
        public int Book_ID { get; set; }
        public string isbn { get; set; }
        public string bookName { get; set; }
        public string description { get; set; }
        public Nullable<int> price { get; set; }
        public string image { get; set; }
        public Nullable<int> quantityExists { get; set; }
        public Nullable<int> sellNumber { get; set; }
        public Nullable<int> saleOffPrice { get; set; }
        public Nullable<bool> statusSaleOff { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<int> language_id { get; set; }
        public Nullable<int> supplier_id { get; set; }
        public Nullable<int> star { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Authors_Books> Authors_Books { get; set; }
        public virtual Category Category { get; set; }
        public virtual Language Language { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailBill> DetailBills { get; set; }
    }
}
