//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_BookStoreCT.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailBill
    {
        public int Bill_ID { get; set; }
        public int Book_ID { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Book Book { get; set; }
    }
}
