//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_BookStoreCT.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int User_ID { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public string avatar { get; set; }
        public string email { get; set; }
        public string phoneNumber { get; set; }
        public Nullable<bool> sex { get; set; }
        public string address { get; set; }
        public Nullable<int> role { get; set; }
    
        public virtual Role Role1 { get; set; }
    }
}
